homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude 
  longitude: !secret longitude 
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Customization file
  customize: !include customize.yaml
  #packages: !include_dir_named packages 

#https://home-assistant.io/components/config/
config:

#https://home-assistant.io/components/history/
history:

#https://www.home-assistant.io/integrations/frontend/
frontend:
  themes: !include_dir_merge_named themes

#https://www.home-assistant.io/integrations/mobile_app/
mobile_app:

#https://www.home-assistant.io/integrations/automation/
automation:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Discover some devices automatically
discovery:

cloud:

ecobee:
  api_key: !secret ecobee_api
  
zwave:
  usb_path: /dev/ttyUSB0
  network_key: !secret zwave_network_key

zha:
  usb_path: /dev/ttyUSB1
  database_path: /config/zigee.db

binary_sensor:
  - platform: wyzesense
  - platform: template
    sensors:
      testing:
        friendly_name: "Binary Sensor Test"  
        value_template: >-
          {{ false }}  

google:
  client_id: !secret google_id
  client_secret: !secret google_secret
    
rachio:
  api_key: !secret rachio_api_key
    
weather:
  - platform: darksky
    api_key: !secret dark_sky_key
    mode: daily
    scan_interval:
      hours: 1
    
zone: 
  - name: Work
    icon: mdi:briefcase-account
    latitude: !secret d_work_latitude
    longitude: !secret d_work_longitude
    radius: 100

ecovacs:
  username: !secret ecovac_username
  password: !secret ecovac_password
  country: us
  continent: na 

#https://www.home-assistant.io/lovelace/yaml-mode/
lovelace:
  mode: yaml 

notify:
  - name: pushover
    platform: pushover
    api_key: !secret pushover_api_key
    user_key: !secret pushover_user_key   

alert:
  freezer_open_alert:
    name: "Kitchen Freezer open"
    entity_id: binary_sensor.wyzesense_778a7b1e
    state: 'on'
    repeat: 3
    skip_first: true
    notifiers:
      - pushover
  garage_freezer_open_alert:
    name: "Garage Freezer open"
    entity_id: binary_sensor.kaipule_technology_co_ltd_im20_door_window_sensor_sensor_2
    state: 'on'
    repeat: 3
    skip_first: true
    notifiers:
      - pushover
  garage_fridge_open_alert:
    name: "Garage Fridge open"
    entity_id: binary_sensor.kaipule_technology_co_ltd_im20_door_window_sensor_sensor
    state: 'on'
    repeat: 3
    skip_first: true
    notifiers:
      - pushover   
  test_sensor_alert:
    name: "Duncan Is Testing"
    entity_id: binary_sensor.testing
    state: 'on'
    repeat: 3
    skip_first: false
    can_acknowledge: true
    notifiers:
      - pushover  

cover:
  platform: opengarage
  covers:
    garage:
      host: !secret opengarage_host
      name: Garage Door    
      device_key: !secret opengarage_key      

#https://www.home-assistant.io/components/speedtestdotnet/
speedtestdotnet:
  server_id: 25239
  monitored_conditions:
    - download
    - upload

#https://www.home-assistant.io/components/system_health/
system_health:

#https://www.home-assistant.io/integrations/tuya/
# tuya:
#   platform: tuya
#   username: !secret tuya_username
#   password: !secret tuya_password
#   country_code: 1

#https://home-assistant.io/components/logger/
logger:
  default: error
###########################################
## Includes
###########################################

#remote: !include remote.yaml  