name: "Run action"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    name: STABLE - Home Assistant Config Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Run Config Check
      uses: ludeeus/action-ha-config-check@master
      with:
        version: DEV
